# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Fetch the private source
      run: git clone https://Et7f3:"${{ secrets.PING_TOKEN }}"@github.com/PingusEpitus/ping . --branch rm_epita --depth 1
    - name: Remove failling test
      run: del .\src\test\java\fr\epita\assistants\utils\PathUtilsTest.java
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: jpackage --input target/ --name Pingus --main-jar ping-ref-1.0.0-SNAPSHOT.jar --main-class fr.epita.assistant.myide.domain.GUI.TestSwing --type msi
    - run: ls
    - uses: actions/upload-artifact@v2
      with:
        name: Pingus-1.0.msi
        path: .
